# See https://github.com/dart-lang/mono_repo for details
stages:
  - format:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - dartfmt
      dart: [dev]
  - analyze:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - dartanalyzer: --fatal-infos .
      dart: [dev]
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - dartanalyzer: .
      dart: [2.10.5]
  - run_tests:
    - group:
      - command: ./../tool/setup.sh
      - command: make protos
      - test
      dart: [2.10.5, dev]
